### ISSUE TITLE
Global examples - sims notebook - missing data

### ISSUE THREAD

**Issue by RichardScottOZ** [Geodels/goSPL-examples#2]
trying a wsl version 

```bash
mpirun -np 8 python3 runModel.py -i input-cont.ym
```

Should this be in the repo, or do we get from elsewhere?

```python
`x$ mpirun -np 8 python3 runModel.py -i input-cont.yml
Unable to open numpy dataset: vars_25_80/mesh.npz
Traceback (most recent call last):
  File "/home/richard/miniconda3/envs/gospl/lib/python3.11/site-packages/gospl/tools/inputparser.py", line 172, in _readDomain
Unable to open numpy dataset: vars_25_80/mesh.npz
Traceback (most recent call last):
  File "/home/richard/miniconda3/envs/gospl/lib/python3.11/site-packages/gospl/tools/inputparser.py", line 172, in _readDomain
    with open(self.meshFile) as meshfile:
    with open(self.meshFile) as meshfile:
         ^^^^^^^^^^^^^^^^^^^
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'vars_25_80/mesh.npz'
```

**Comment by tristan-salles** [comment]
I think it depends on how far you went in the build_inputs notebook. If ran completely you should have a folder named:
`vars_25_80` in the `continental_flux` folder. If you stoped at the first mesh generation you will have a folder named: `vars_30` and you could use this one instead by changing the path in the `input-cont.yml`:

 ```yaml
domain:
      npdata: ['vars_30/mesh','v','c','z']
      flowdir: 2
      seadepo: False
```

and here:
  
 ```yaml
  climate:
    - start: 250.e6
      uniform: 2
```

**Comment by RichardScottOZ** [comment]
Right, will check thanks
